### ISSUE TITLE
 网关事件OnValueChanged

### ISSUE THREAD

**Issue by SmallShrimp** [GavinYellow/SharpSCADA#11]
当opc Server断开一次，然后网关重新连接到server时，OnValueChanged事件就不再触发了。通过IDataExchangeService服务获取标签的值就永远停在OpcServer断开的时候的值

**Comment by GavinYellow** [comment]
我需要确认下，是否是OPCGroup的Datachange事件不再触发还是“OnValueChanged”未触发。

**Comment by SmallShrimp** [comment]
![image](https://user-images.githubusercontent.com/8120385/33416493-cf681792-d5d7-11e7-9f57-ab1db7f9af2d.png)
这里注册的OnValueChanged不再进去了 ，之前是要不断的进入这个方法，但是断开一次后就不再进入了，然后tag的值就停在最后一次的值

**Comment by GavinYellow** [comment]
其实这个Vlauechanged是和报警相关的。真正数据变化触发是在Group的Datachanged事件批量推送。
