### ISSUE TITLE
提供一个连接远程数据库的参考配置文件

### ISSUE THREAD

**Issue by cuihee** [GavinYellow/SharpSCADA#26]
将工程目录内的./DataConfig文件夹复制到C盘
修改C:/DataConfig/host.ini文件内容
参考如下

[HOST]

SERVER=lochost

[DATABASE]

CONNSTRING=Data Source=192.168.1.207,1433;Database=SCADA;User=sa;Password=;

ARCHIVE=D:\HDA

TYPE=MSSQL

//==========我是分割线=============
主要修改连接字符串，之后可以打开tagconfig

第二行SERVER不知道是什么意思
第五行ARCHIVE不知道是什么意思
希望能得到一些解释

**Comment by inmen** [comment]
第二行SERVER   用了默认机器名称
第五行ARCHIVE 用来存放从数据库归档出的文件
