### ISSUE TITLE
提供一个ModbusTCP数据点地址的填写样例

### ISSUE THREAD

**Issue by cuihee** [GavinYellow/SharpSCADA#27]
在TagConfig里面，
右键服务器-新建
右键你新建出来的device-参数配置
新窗口里面选择ModbusTCP并填写服务器地址-关闭

右键你新建出来的device-增加
点选你新建出来的group，右边增加
给新建出来的标签tag取个名字，第二列地址的填写是本issue正题：

1. 你需要知道Modbus有四种常用命令：读写线圈boolean、读离散boolean、读写寄存器、读寄存器

2. 一个地址形如00020，第一个0表示它是读写线圈的命令。一个地址形如40033，第一个4表示它是读写寄存器的命令。地址的后四位是modbus中地址号（有些modbus地址号从0开始有些不是）

3. ModbusTCPReader.GetDeviceAddress记录了更详细的的信息

**Comment by cuihee** [comment]
阅读理解源码发现，使用如下形式添加指定mosbud站号
5:00020
5:40033
读写站号为5的线圈或寄存器

另外发现了形如
5:00020.9
这样的写法，但是不清楚小数点后面的数字是什么意思

**Comment by fansjay** [comment]
发件人: noreply@github.com <noreply@github.com> 代表 cuihe
发送时间: 2019年6月6日 9:22
收件人: GavinYellow/SharpSCADA <SharpSCADA@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [GavinYellow/SharpSCADA] 提供一个ModbusTCP数据点地址的填写样例 (#27)

 

阅读理解源码发现，使用如下形式添加指定mosbud站号
5:00020
5:40033
读写站号为5的线圈或寄存器

另外发现了形如
5:00020.9
这样的写法，但是不清楚小数点后面的数字是什么意思

—ok

**Comment by cuihee** [comment]
小数点后的数字表示位，并不是每种类型的读写都有效，似乎只有读写boolean类型的值有效

至此，地址解释完毕
