### ISSUE TITLE
TargetInvocationException

### ISSUE THREAD

**Issue by mridah** [GavinYellow/SharpSCADA#31]
I'm getting the following exception when I run `BatchCoreTest.exe`:

![image](https://user-images.githubusercontent.com/21169606/79876548-cfda0c80-8408-11ea-90dc-9ca200815d20.png)

`CoreTest.exe` and `TagConfig.exe` don't run.

I'm trying to use with MySQL. I've imported the mysql file into a new database named `scada`

I've made the following changes to `host.ini`:

    CONNSTRING=server=localhost;user id=root;password=my_pass;database=scada
    TYPE=MYSQL

and the following changes to `host.cfg`:

    server=localhost;user id=root;password=my_pass;database=scada

Also I've placed the folder `DataConfig` in C:\ drive

What am I missing ?? @GavinYellow @yangjingzhao123  @dathlin

**Comment by kevin100702** [comment]
run as adminitrator

**Comment by yuxiang8910** [comment]
closed




秋夜雨寒Oo。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GavinYellow/SharpSCADA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 下午5:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [GavinYellow/SharpSCADA] TargetInvocationException (#31)





 
Closed #31 as completed.
