### ISSUE TITLE
我用的是vs2022 设计器，我把LinkableControlDesign 的引用换成了最新的，没法在设计的时候拿到linkpin,无法连线

### ISSUE THREAD

**Issue by Chickenbrother** [GavinYellow/SharpSCADA#38]
在我不更新库的时候，也不能够运行，请作者指点下。编译没有报错

**Comment by mazhongbin** [comment]
您好：    您的来信已收到，查阅后尽快与您取得联系。

**Comment by Chickenbrother** [comment]
谢谢您

**Comment by Chickenbrother** [comment]
> 您好：    您的来信已收到，查阅后尽快与您取得联系。

您好，我换了visual studio 2019 version 16.9 可以出现连线的连接点。但是visual studio 2022 上无法使用。

**Comment by kevin100702** [comment]
vs2022的整个插件的运行机制已经改变了，目前开源版的没办法进行兼容
